spring:
  datasource:
    url: jdbc:sqlite:library.db
    username: sa
    password: sa
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
    schema: schema.sql
    data: data.sql